### ISSUE TITLE
Property specified as `Number` but returns a string

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-range-behavior#12]
https://github.com/PolymerElements/iron-range-behavior/blob/master/iron-range-behavior.html#L29 returns `"5"` instead of `5.0`.
See also dart-lang/polymer_elements#74

**Comment by blasten** [comment]
hmm. I think you are using paper-slider is that correct?

**Comment by zoechi** [comment]
Yes, I was working on porting the paper-slider demo to Dart

**Comment by blasten** [comment]
related to https://github.com/PolymerElements/paper-slider/issues/92
