### ISSUE TITLE
Polymer object is undefined on IE11 due to use of behaviors

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-range-behavior#7]
_From @dimshik100 on June 15, 2015 13:13_

while checking the iron-range-behavior from your catalog on ie11, I've got the following exception: 'Polymer' is undefined.

sample link: https://elements.polymer-project.org/elements/iron-range-behavior?active=Polymer.IronRangeBehavior&view=demo:demo/index.html

Also tried iron-range-behavior uni-test from polymer-starter-kit, they all fail on IE11.
http://<polymer-starter-kit host>/bower_components/iron-range-behavior/test/index.html

It looks like IE11 have some issues with polymer behaviors.

_Copied from original issue: Polymer/polymer#1871_

**Comment by tjsavage** [comment]
_From @kevinpschaaf on June 16, 2015 1:41_

The call to `Polymer` in the demo needs to be wrapped in `HTMLImports.whenReady`.

**Comment by blasten** [comment]
@dimshik100 this has been fixed!
